### PR TITLE
Fix my own typo

### PR DESCRIPTION
**Pull request by samip5**

### CODE REVIEW

**Comment by bugfest** [comment]
Thanks @samip5! I think I made a change to fix it just 1 min before I got the PR :_ ) going to wait for the build to finish and hopefully we'll have multiarch thanks to you!

**Comment by bugfest** [comment]
the build is still ongoing. It took 30min to get tor-controller done, is now multiarch :D

**Comment by samip5** [comment]
> the build is still ongoing. It took 30min to get tor-controller done, is now multiarch :D

It took ~15 minutes at least on native arm64 ;)

**Comment by bugfest** [comment]
LOL, it's it ok then. qemu FTW

**Comment by samip5** [comment]
The fact it compiles Tor from source is the reason it takes so long. :D

**Pull request closed without merging**
