### PR TITLE
Linting, formatting and error wrappers

### PR DESCRIPTION
**Pull request by lexfrei**
Small improvements:
- Linting
- Formatting
- Errors creating
- `fmt` removed where possible
- `github.com/cockroachdb/errors` used as a replacement for deprecated "std" `errors`

### CODE REVIEW

**Comment by lexfrei** [comment]
It looks like the `log.Info()` is misused. Probably, we can drop all direct "fmt" imports
[Proof](https://pkg.go.dev/github.com/go-logr/logr#section-readme:~:text=to%20request%20easier.-,But%20I%20really%20want%20to%20use%20a%20format%20string!,-That%27s%20not%20actually).

**Comment by lexfrei** [comment]
Looks like there are a lot of commented code lines. Do you need them as notes or should they be removed?

**Comment by bugfest** [comment]
Thanks @lexfrei ! Quite a job here. I do agree to drop commented lines of code if I spot anything interesting that otherwise I forget I'll put a comment

**Comment by lexfrei** [comment]
`"io/ioutil"` dropped as deprecated, replaced with `os`

For now, I think, the main cleanup is done. There are a lot of possible improvements, but the biggest part of simple changes is done.

In this work, I used this golangci-lint [config](https://github.com/lexfrei/tools/blob/master/.golangci.yaml).
You can add it to your repo along with this action. But for now, it will fail.

**Comment by bugfest** [comment]
> `"io/ioutil"` dropped as deprecated, replaced with `os`
> 
> For now, I think, the main cleanup is done. There are a lot of possible improvements, but the biggest part of simple changes is done.
> 
> In this work, I used this golangci-lint [config](https://github.com/lexfrei/tools/blob/master/.golangci.yaml). You can add it to your repo along with [this](https://github.com/lexfrei/tools/blob/master/.github/workflows/lint-go.yaml) action. But for now, it will fail.



> `"io/ioutil"` dropped as deprecated, replaced with `os`
> 
> For now, I think, the main cleanup is done. There are a lot of possible improvements, but the biggest part of simple changes is done.
> 
> In this work, I used this golangci-lint [config](https://github.com/lexfrei/tools/blob/master/.golangci.yaml). You can add it to your repo along with [this](https://github.com/lexfrei/tools/blob/master/.github/workflows/lint-go.yaml) action. But for now, it will fail.

Thanks for the suggestion @lexfrei - I've opened #46 track/implement the action.

Will run the build and merge when it finshes. Thanks for all this work!!

**Pull request merged**
