### PR TITLE
update: minor fixes; consistenecy

### PR DESCRIPTION
**Pull request by codekow**
- update: docs
- update: values w/ security
- fix: perms on `/run/tor/service`
- fix: non root on containers

### CODE REVIEW

**Comment by codekow** [comment]
These updates came from testing https://github.com/bugfest/tor-docker/pull/7

**Comment by bugfest** [comment]
Thanks @codekow, It will take me some time to review all these changes; please group changes in separate PRs so it's easier to track; I'll start with the docker-tor PR. Happy to stop using uid 0

**Comment by codekow** [comment]
@bugfest Sorry for the chaotic nature of the PR. I'll try to keep the PRs smaller and easier to track in the future.

I have tested the changes in both minishift and OpenShift.

**Comment by bugfest** [comment]
https://github.com/bugfest/tor-docker/pull/7 merged; build in progress

**Review by bugfest — APPROVED** [review]

**Pull request merged**
